version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:10.19.0
    steps:
      - checkout        
      - run:
          name: Updating apt-get
          command: sudo apt-get update
      - run:
          name: Installing wget
          command: 'sudo apt-get install wget zip unzip'
      - run:
          name: Install node dependencies 
          command: | 
            npm install
      - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get install python-pip
            sudo pip install awscli
      - run:
          name: Install less
          command: |
            echo "Install less dependency"
            sudo apt-get update
            sudo apt-get install less -y
      - run:
          name: Zip Artifact
          command: |
            cd ~/
            cd project
            zip -r lambda.zip *
            ls -al
      - run:
          name: Uploading Artifact to S3
          command: |
            aws s3 cp lambda.zip s3://${S3_BUCKET_NAME}/lambda.zip
      - run:
          name: Make Lambda function update call
          command: |
            aws lambda update-function-code --function-name Reset-Password --region us-east-1 --zip-file fileb://lambda.zip
workflows:
  version: 2
  build_deploy:
    jobs:
    - deploy
